---
title: "eda"
format: html
editor: visual
---

## Statement of the Research Question & Analysis Objective:

### Research Question:

What are the main factors that contribute to the distribution of haunted locations throughout the United States? How many locations are there of each category in the following list:

-   tragic or historical events

-   unexplained phenomena

-   burial grounds and cemeteries

-   legends and folklore

-   psychical or paranormal research

-   cultural and religious beliefs

### Analysis Objective:

Our primary objective is to analyze the dataset of haunted locations in the United States to understand the factors that lead to their designation as haunted. Specifically, we aim to:

-   Analyze the descriptions within the dataset: We will examine the descriptions provided in the dataset to determine whether most haunted location are caused by certain events or by unexplained phenomena.

-   Based on the descriptions, we can categorize each location into the groups mentioned in the Research Question section and ascertain the number of events attributed to each category.

## Description of the Data

The most important variable from our dataset is the "description." We will reply on this variable to answer our research questions.

Because description contains sentences that explaining why the location is considered haunted, we can use a search algorithm to identify specific keywords within these sentences. These keywords will help filter and sort out our data. For instance, if a sentence in the description contains words like "killed" or "death," then we can classify the location under the category of tragic or historical events.

## Exploratory Data Analysis
